- server/grpcservice/error.go
- server/grpcservice/handler.go
- server/grpcservice/service.go
- server/schedule/error.go
- server/schedule/hbstream.go
- server/server.go
Part of work of #10 
The heartbeat stream from clients needs management by `HeartbeatStreams` including `Bind`, `Unbind` etc.
Introduce the `HeartbeatStreams` to manage heartbeat streams from clients.
> feat: support managing heartbeat

- Makefile
- README.md
- cmd/meta/main.go
- pkg/coderr/code.go
- pkg/coderr/error.go
- pkg/log/config.go
- server/config/config.go
- server/config/error.go
- server/member/member.go
- server/server.go
Closes #13
Now the ceresmeta is actaully not runnable. Make it runnable before the following work comes.
- Fix the problem the process can't exit after receive interupt signal.
- Make the etcd log level and file configurable.
- Set name for `Member`.
> feat: make ceresmeta runnable in cluster mode

- .gitignore
- server/member/lease.go
- server/member/member.go
- server/member/watch_leader.go
- server/member/watch_leader_test.go
- server/server.go
Closes #
Some data is exclusive and can only be kept by the leader, that is to say, these data can't be accessed by followers and leaders at the same time. Such a requirement is a little difficult to be met when the leadership is being transferred.
What we need is actually is a mechanism to enforce then order of the leadership transference between the old leader and the new leader so that we can disallow the old leader access to the exclusive data before the old leader transfers the leadership and allow the new leader access to the data before the new leader takes the leadership.
Introduce the `LeadershipEventCallbacks` to the `Leadership.Watch` method and the callbacks will be called before the leader hands over the leadership and after the leader takes up the leadership.
None.
There is …
> feat: support leadership event callback mechanism

- README.md
Closes #
CeresMeta is the meta service for managing the CeresDB cluster. 
Before starting CeresDB cluster, we need start ceresmeta service first.
Add `Quick Start` in README to help developers start ceresmeta.
> docs: add `Quick Start` in README

- .github/workflows/check.yml
- Makefile
- go.mod
- server/member/watch_leader.go
- server/server.go
- server/storage/etcd_kv.go
- server/storage/key_path.go
Closes #49 
The style for doc comment has been updated with the go1.19 release, so some doc comments needs fixing.
- Update the go version to 1.19;
- Fix some comment style;
None.
CI ensures this.
> chore: update golang to 1.19.1

- .github/pull_request_template.md
- docs/style_guide.md
- pkg/coderr/error.go
- pkg/coderr/error_test.go
- server/cluster/cluster.go
- server/cluster/coordinator.go
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/etcdutil/config.go
- server/etcdutil/util_test.go
- server/grpcservice/forward.go
- server/grpcservice/service.go
- server/id/id_impl.go
- server/id/id_test.go
- server/member/watch_leader_test.go
- server/schedule/event_handler.go
- server/server.go
- server/storage/storage_impl.go
Closes #20 
The call stack should be attached to the error cause, which helps a lot when troubleshooting problems.
- Replace `errors.Wrap(f)` with `errors.WithMessage(f)`;
- Attach call stack to `coderr` cause;
- Some fixes for docs;
None.
New ut.
> refactor: attach call stack to coderr

- server/coordinator/procedure/procedure.go
- server/coordinator/procedure/storage.go
- server/coordinator/procedure/switch_leader.go
Closes #
`Procedure` is used to describe how to execute a set of operations of the procedure.
All procedures like `SwitchLeaderProcedure` and `MergeShardProcedure` need to implement `Procedure`.
Define `Procedure` interface.
No.
No.
> feat: define procedure interface

- revive.toml
Closes #64 
CI should fail when encountering revive lint warnings.
Set `warningCode = 1` in revive config, ci will fail when encountering revive lint warnings .
Refer to https://github.com/mgechev/revive/blob/a4add4a769339021d98d1cbf241a4b043957ac93/README.md.
No.
No need.
> feat: set warningCode = 1 in revive config

- server/coordinator/procedure/storage.go
- server/coordinator/procedure/storage_impl.go
- server/coordinator/procedure/storage_test.go
- server/etcdutil/util.go
https://github.com/CeresDB/ceresmeta/issues/62
Implementation of procedure storage based on `etcd`, and expose appropriate interfaces externally.
* Add `Delete` func to `Write` interface
* Add implementation for `EtcdStorageImpl`
* Add test for `EtcdStorageImpl`
None.
> feat: add procedure storage implementation

- server/cluster/cluster.go
- server/cluster/manager.go
- server/cluster/shard.go
- server/id/error.go
- server/id/id.go
- server/id/id_impl.go
- server/id/reusable_id_impl.go
- server/id/reusable_id_test.go
Closes #
To manage the scheduling of shards, we need to generate and manage the ID of shards just like Table.
Add ShardID allocator for every cluster instance
None
Reuse the existing allocator implementation, and unit tests already exist.
> feat: add shardID allocator

- server/cluster/cluster.go
- server/coordinator/procedure/common_test.go
- server/coordinator/procedure/scatter.go
- server/coordinator/procedure/scatter_test.go
- server/coordinator/procedure/transfer_leader.go
- server/coordinator/procedure/transfer_leader_test.go
- server/coordinator/procedure/util.go
https://github.com/CeresDB/ceresmeta/issues/66
As mentioned in issue, add a procedure implementation
Add `TransferLeaderProcedure` implementation 
None.
> feat: add transfer leader procedure

- server/cluster/cluster.go
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/cluster/shard.go
- server/coordinator/procedure/common_test.go
- server/coordinator/procedure/create_table.go
- server/coordinator/procedure/create_table_test.go
- server/coordinator/procedure/error.go
- server/coordinator/procedure/procedure.go
- server/coordinator/procedure/scatter.go
- server/coordinator/procedure/scatter_test.go
- server/coordinator/procedure/transfer_leader.go
- server/coordinator/procedure/util.go
- server/service/grpc/service.go
Closes #
Add CreateTableProcedure implementation.
* Modify function in cluster
```
GetOrCreateTable(ctx context.Context, nodeName string, schemaName string, tableName string) (*Table, error)
->GetOrCreateTable(ctx context.Context, nodeName string, schemaName string, tableName string) (*Table, bool, error)
```
* Add `GetShardByID` function in `cluster.Shard`.
*  Add CreateTableProcedure implementation.
Add `TestCreateTable` test.
> feat: add CreateTableProcedure

- pkg/coderr/code.go
- server/cluster/cluster.go
- server/cluster/error.go
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/cluster/node.go
- server/cluster/types.go
- server/coordinator/eventdispatch/dispatch_impl.go
- server/coordinator/procedure/factory.go
- server/coordinator/procedure/scatter.go
- server/server.go
- server/service/grpc/service.go
- server/service/util.go
Fix some problem when debugging scatter locally.
* Move `CreateShardTopologies` to `ScatterProcedure`, solve hard coding problem of shardID
* Avoid `GetTables`  throw error when `ScatterProcedure` send `OpenShardRequest` to CeresDB. In this case,  shard has not yet been created
* When `ScatterProcedure` start and `ClusterTopologyState` is `Empty` , just print some warning log instead of cancel event.
None.
> fix: fix some scatter error

- server/coordinator/procedure/error.go
- server/coordinator/procedure/scatter.go
https://github.com/CeresDB/ceresmeta/issues/74
Rebuild cluster topology based on metadata when restarted, recover to stable state.
* Add `rebuildTopology` function, it will be rebuild cluster when `CeresMeta` leader node restarts.
None.
> feat: add rebuild topology

- server/cluster/node.go
- server/cluster/shard.go
- server/coordinator/procedure/scatter.go
- server/coordinator/scheduler.go
- server/server.go
Closes # https://github.com/CeresDB/ceresmeta/issues/76
Providing Basic failover capability of CeresDB cluster mode.
* Add `ProcedureScheduler` implementation.
* Add node crash detection in `checkNodeState`.
* Procedure scheduler automatically submit `TransferLeaderProcedure` when node crashed.
None.
> feat: add procedure scheduler

- server/service/util.go
Closes # https://github.com/CeresDB/ceresmeta/issues/88
It has been mentioned in the issue.
Add `addr` format check in `GetClientConn`, parse `addr` when it's prefix is http. 
None.
Manually tested in the local environment.
> fix: fix input address format mistake

- go.mod
- go.sum
- server/config/config.go
- server/server.go
- server/service/http/api.go
- server/service/http/error.go
- server/service/http/route.go
- server/service/http/service.go
None.
CeresMeta currently only includes grpc server, not http server. But http interface need to be provided for some operation and maintenance operations.
* Import third-party library `httprouter`, it is used for simplify server development. https://github.com/julienschmidt/httprouter
* Implement http server based on `httprouter` and `http` in standard library.
None.
> feat: add http server

- Makefile
- go.mod
- go.sum
- server/cluster/table_manager_test.go
- server/cluster/types.go
- server/coordinator/eventdispatch/dispatch_impl.go
- server/coordinator/procedure/create_drop_table_test.go
- server/coordinator/procedure/create_table.go
- server/coordinator/procedure/drop_table.go
- server/coordinator/procedure/factory.go
- server/coordinator/scheduler.go
- server/member/member.go
- server/server.go
- server/service/grpc/forward.go
- server/service/grpc/service.go
- server/storage/storage_impl.go
- server/storage/types.go
Closes #
Dirs of underlying dependency `ceresdbproto` has been changed, bump to the latest version and do some related adaption
1. Dependency description for `ceresdbproto` has been modified.
2. Import path of several packages has been adpapted.
nope.
Pass the existing CI.
> chore: bump ceresdbproto to the latest version

- cmd/meta/main.go
- config.toml
- go.mod
- go.sum
- server/config/config.go
Closes #
At present, ceresmeta's startup parameters only support specifying in program arguments. These configurations are difficult to maintain. We want to specify startup parameters by setting configuration files. 
* Add toml config parser, it will parse toml config when ceresmeta starts.
* Add a sample toml config example.
User can configure the startup parameters by input toml file path now.
> chore: add toml config parser

- server/server.go
Closes #
Now the http server will be started when the meta starts synchronously, this will cause the meta server to fail to initialize normally.
* Change the start of http server from synchronous to asynchronous.
None.
> fix: fix http server start

- server/cluster/error.go
- server/cluster/table_manager.go
- server/cluster/types.go
- server/coordinator/scheduler.go
- server/service/grpc/service.go
- server/service/http/api.go
- server/storage/storage_impl.go
- server/storage/types.go
Closes #
Fix some bugs introduced due to refactoring code, enables the cluster to be deployed normally.
* The values in type enum and pb do not correspond., correct the enum values in type, make them consistent with pb.
* Add http route interface.
None.
> chore: add route http interface & fix some bugs

- cmd/meta/main.go
- pkg/log/config.go
- server/config/config.go
Closes #
At present, the server startup parameters do not support input through environment variables. We need to write some configurations in the configuration file, which is very inflexible. We hope to directly inject parameters through environment variables.
* Add env variables parser.
The user can now configure the startup parameters of the server through the environment variables.
> chore: add env variable config parser

- server/cluster/topology_manager.go
Closes #
Fix the bug that tableID cannot be added normally when creating a table.
* Replace `copy` method with `append`.
None.
Add multi tables create test. @chunshao90
> fix: fix shard view copy table

- cmd/meta/main.go
- server/cluster/table_manager.go
Closes #
When server restart, it will reload all metadata in memory, but schema table mapping is not initialized normally.
* Fix schema table mapping initialization.
* Fix the initialization problem of the logger to avoid invalid log configuration.
None.
> fix: fix load schema table mapping & logger initialization

- server/cluster/cluster.go
- server/cluster/table_manager.go
- server/cluster/topology_manager.go
- server/coordinator/procedure/create_table.go
Closes #
There is a very serious bug when creating an existing table will cause the old table to be deleted.
Remove `dropTable` rollback when `createTable` failed.
No.
Manual testing.
> fix: remove dropTable rollback when createTable failed

- config.toml
- server/cluster/cluster.go
- server/cluster/topology_manager.go
- server/cluster/types.go
- server/coordinator/procedure/common_test.go
- server/coordinator/procedure/create_drop_table_test.go
- server/coordinator/procedure/drop_table.go
- server/coordinator/procedure/factory.go
- server/coordinator/procedure/scatter.go
- server/coordinator/procedure/scatter_test.go
- server/coordinator/procedure/split.go
- server/coordinator/procedure/split_test.go
- server/coordinator/procedure/transfer_leader.go
- server/coordinator/procedure/util.go
- server/coordinator/scheduler.go
- server/server.go
- server/service/grpc/service.go
- server/service/http/api.go
- server/service/http/error.go
Closes https://github.com/CeresDB/ceresmeta/issues/66
It has been mentioned in the issue, add split procedure implementation.
* Add split procedure implementation in `split.go`.
* Implement split http interface in `api.go`.
* The capacity expansion of CeresDB node is realized through the combination of split and transferleader in `api.go`.
None.
> feat: add split procedure

- go.mod
- go.sum
- server/cluster/cluster.go
- server/cluster/manager.go
- server/cluster/table_manager.go
- server/cluster/table_manager_test.go
- server/cluster/types.go
- server/config/config.go
- server/coordinator/procedure/ShardPicker.go
- server/coordinator/procedure/common_test.go
- server/coordinator/procedure/create_drop_table_test.go
- server/coordinator/procedure/create_normal_table.go
- server/coordinator/procedure/create_partition_table.go
- server/coordinator/procedure/create_partition_table_test.go
- server/coordinator/procedure/create_table.go
- server/coordinator/procedure/create_table_common_util.go
- server/coordinator/procedure/error.go
- server/coordinator/procedure/factory.go
- server/coordinator/procedure/procedure.go
- server/coordinator/procedure/scatter_test.go
- server/coordinator/procedure/shard_picker.go
- server/coordinator/procedure/shard_picker_test.go
- server/coordinator/procedure/split_test.go
- server/coordinator/procedure/transfer_leader.go
- server/coordinator/procedure/trasnfer_leader_test.go
- server/coordinator/procedure/util.go
- server/server.go
- server/service/grpc/service.go
- server/storage/types.go
(https://github.com/CeresDB/ceresdb/issues/492)
Support create partition table in CeresDB.
* Add implementation of `CreatePartitionTableProcedure`.
* Add `ShardPicker` for picking up the shards suitable for scheduling in the cluster.
None.
> feat: add create partition table procedure

- go.mod
- go.sum
- server/coordinator/eventdispatch/dispatch.go
- server/coordinator/eventdispatch/dispatch_impl.go
- server/coordinator/procedure/create_partition_table.go
- server/coordinator/procedure/create_partition_table_test.go
- server/coordinator/procedure/create_table.go
- server/coordinator/procedure/create_table_common_util.go
- server/coordinator/procedure/factory.go
Closes #
To support creation of partition tables, we have updated the data structure in `ceresdbproto` and added `encodedPartitionInfo`. CeresMeta also needs to adapt to this adjustment.
* Update `ceresdbproto`
* Adapt to new data structures.
None.
Pass the existing unit test.
> chore: update ceresdbproto & adapter to partition info

- config/example-cluster1.toml
- config/example-cluster2.toml
- server/coordinator/procedure/common_test.go
- server/coordinator/procedure/create_partition_table_test.go
- server/coordinator/procedure/error.go
- server/coordinator/procedure/factory.go
- server/coordinator/procedure/shard_picker.go
- server/coordinator/procedure/shard_picker_test.go
- server/coordinator/procedure/split_test.go
Closes #
Support the creation of sub tables on the same node. 
* Update `shardPicker` interface, add `allowSameNode` param, it enable pick shards on the same node.
* Fix server start config.
* Partition table could be created when partition number is bigger than node number. 
> feat: support alloc shard on same node

- server/config/config.go
Closes #
Because of the limitation of etcd on single txn ops (128 by default), when the cluster is configured with a large number of shards, etcd will fail to write. Therefore, it is necessary to provide a configuration entry to adjust the maxTxnOps.
* Add EtcdMaxTxnOps in start config.
* Start etcd server with EtcdMaxTxnOps.
None.
> feat: add etcd max txn ops config

- server/server.go
- server/service/http/api.go
- server/service/http/error.go
- server/service/http/forward.go
Closes #
When CeresMeta is started in the cluster mode, the cluster contains the leader node and follower node, and only the leader node can process requests normally. However, the current http requests sent to the follower node are not forwarded like grpc requests, which will result in that the requests cannot be processed normally.
* Add http forward client implementation.
* Add forward logic, follower node will forwarded request to leader node.
None.
> feat: support forwarding http requests

- server/cluster/cluster.go
- server/cluster/topology_manager.go
- server/cluster/types.go
- server/coordinator/eventdispatch/dispatch.go
- server/coordinator/eventdispatch/dispatch_impl.go
- server/coordinator/procedure/common_test.go
- server/coordinator/procedure/create_partition_table.go
- server/coordinator/procedure/drop_partition_table.go
- server/coordinator/procedure/factory.go
- server/service/http/forward.go
Closes #
When creating partition table, CeresMeta need to open tables on multiple shards, but CeresDB only supports open/close shard interface, so we implement open table by reopen shard. This is an inefficient way, which will cause shard to be unavailable during table creation. It's should be replaced with open table after CeresDB provides new interface.
* Add `OpenTableOnShard` implementation in `DispatchImpl`.
* Replace `CloseShard` and `OpenShard` with `OpenTableOnShard`.
* Fix missing param `UpdateShardVersion` in `DropPartitionTableProcedure`.
Shard can work normally when creating/drop partition tables.
Pass existing unit tests.
> refactor: replace reopen shard with open table

- go.mod
- go.sum
- server/cluster/cluster.go
- server/cluster/table_manager.go
- server/cluster/table_manager_test.go
- server/cluster/types.go
- server/config/config.go
- server/coordinator/eventdispatch/dispatch.go
- server/coordinator/eventdispatch/dispatch_impl.go
- server/coordinator/procedure/create_drop_partition_table_test.go
- server/coordinator/procedure/create_partition_table.go
- server/coordinator/procedure/create_table.go
- server/coordinator/procedure/create_table_common_util.go
- server/coordinator/procedure/split_test.go
- server/storage/types.go
Closes #
In order to support the case where the partition table is opened by multiple machines in a non-cloud environment, store the partition info of `PartitionTable` in `ceresmeta`.
* Store partition info of `PartitionInfo` in metadata of the table.
No.
Manual testing.
> feat: store partition info in ceresmeta

- server/cluster/types.go
- server/coordinator/procedure/operation/transferleader/transfer_leader.go
- server/coordinator/scheduler.go
- server/service/http/api.go
- server/service/http/error.go
Closes #
Fix the scheduling and failover bugs found in recent use.
* Add node state check in `TransferLeaderProcedure`.
* Support multi-node concurrent shard opening to speed up replay.
* Add `getShardNodes` interface.
None.
Pass existing unit tests.
> fix: add node state check in transfer leader procedure & Support multi-node concurrent shard opening.

- server/coordinator/lock/entry_lock.go
- server/coordinator/lock/entry_lock_test.go
(https://github.com/CeresDB/ceresmeta/issues/145)
In order to achieve concurrency of procedures at the shard level, we need to implement locks on the shard entity for procedures.
* Implement entry lock in `entry_lock.go`, which support try lock in multi shards.
* Add unit test for entry lock.
None.
Pass the newly created unit test.
> refactor: implement entry lock

- go.mod
- go.sum
- server/coordinator/watch/watch.go
- server/coordinator/watch/watch_test.go
(https://github.com/CeresDB/ceresmeta/issues/145)
In order to ensure that user data in distributed mode will not be lost, we need a mechanism to ensure that CeresDB will not have multiple leader shard under any circumstances. `etcd` lock has been added in https://github.com/CeresDB/ceresdb/pull/706 , we refactor scheduler to implement failover based `etcd` distributed lock.
* Add shard watcher to get notify when shard lock is expired.
None.
> refactor: implement failover based distributed etcd lock

- server/coordinator/procedure/operation/transferleader/transfer_leader.go
- server/coordinator/shard_picker.go
Closes #
The current shard picker uses the cluster instance to dynamically obtain the latest cluster topology. This is wrong. It should be scheduled based on the snapshot of the cluster. In this pull request, use snapshot to replace cluster.
* Modify the `ShardPicker` interface and add the `Snapshot` parameter.
* Modify the implementation to adapt to the current interface.
None.
Unit tests are currently not working properly and will be fixed in a subsequent pull request.
> refactor: refactor shard picker

- server/cluster/metadata/cluster_metadata.go
Closes #
When testing locally, it is found that shardNodes cannot be updated normally when the shardInfo in registerNode is empty.
1. Fix the bug that clusterView cannot be updated normally when the node is registered.
None.
All unit tests pass, and local validation is correct.
> fix: fix update cluster view when shardinfos is empty

- server/cluster/metadata/topology_manager.go
- server/cluster/metadata/types.go
- server/coordinator/node_picker.go
- server/coordinator/node_picker_test.go
- server/coordinator/scheduler/assign_shard_scheduler.go
- server/coordinator/scheduler/rebalanced_shard_scheduler.go
- server/coordinator/scheduler/scheduler_manager.go
- server/hash/consistent_hash_ring.go
- server/hash/consistent_hash_ring_test.go
Closes #
In the current failover implementation, if a node goes down, all its shards will be moved to other shards, and the shards will not be transferred back after the node is restarted, which will cause a lot of pressure on operation and maintenance. We need supports automatic load balancing.
1. Introduced the consistent hash implementation in the golang standard library, ref: https://github.com/golang/groupcache/blob/4a4ac3fbac33b83bb138f808c8945a2812023fc4/consistenthash/consistenthash.go
2. Implemented shard load balancing based on consistent hashing.
None.
Pass all unit tests and local tests.
> feat: add rebalanced shard scheduler

- server/cluster/cluster.go
- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/topology_manager.go
- server/config/config.go
- server/coordinator/scheduler/assign_shard_scheduler.go
- server/coordinator/scheduler/scheduler_manager.go
- server/service/http/api.go
- server/storage/types.go
Closes #
We support automatic failover and load balancing in the latest version, but they are not applicable in some scenarios, so add a switch to control their opening.
* Add `DeployMode` config, When the deployMode is turned on, the failover scheduling will be turned off, which is used for CeresDB cluster publishing and using local storage.
None.
Pass all unit tests and verify that the switch takes effect in the local environment.
> feat: add deploy mode

- server/cluster/cluster.go
- server/cluster/manager.go
- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/table_manager_test.go
- server/cluster/metadata/topology_manager.go
- server/config/config.go
- server/coordinator/procedure/test/common.go
- server/coordinator/scheduler/scheduler_manager.go
- server/server.go
- server/service/grpc/service.go
- server/service/http/api.go
Closes #
Fix some bugs found in release testing.
1. Fix the bug of `getTableOfShard`, now CeresDB can open shard normally.
2. Rename `deployMode` to `schedulerOperator`.
None.
> fix: fix get table of shards.

- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/compare_benchmark_test.go
Closes #
Check whether updates are required during node registration to avoid frequent updates of ClusterVersion and put pressure on ETCD.
* Add verification of node shard information in `RegisterNode` to avoid invalid updates.
None.
> refactor: avoid frequent update of clusterVersion

- server/cluster/metadata/cluster_metadata.go
- server/coordinator/factory.go
- server/service/grpc/service.go
Closes #
Fixed the problem that drop partition table lacked parameters.
* Add `ClusterSnapshot` param to `DropPartitionTableProcedure`.
* Fixed the wrong judgment condition in `sampleCompare` and `sortCompare`.
None.
> fix: fix drop partition table

- server/coordinator/factory.go
- server/coordinator/procedure/ddl/createpartitiontable/create_partition_table_test.go
- server/coordinator/procedure/ddl/droppartitiontable/create_drop_partition_table_test.go
- server/coordinator/procedure/test/common.go
- server/coordinator/shard_picker.go
- server/coordinator/shard_picker_test.go
Closes #
Fix the `% 0` bug that may occur during the cluster initialization phase.
*  Fix the `% 0` bug that may occur during the cluster initialization phase.
* Refactor `PickShards` function.
* Pick shard to random.
No.
CI.
> fix: mod zero

- server/member/member.go
- server/member/watch_leader.go
- server/member/watch_leader_test.go
- server/server.go
- server/service/grpc/forward.go
- server/service/grpc/service.go
- server/service/http/forward.go
Closes #181 
As mentioned in the issue, fix the performance problem of `routeTable`.
* Add leader memory cache in member.
* Correct the `GetLeader` method, get the leader endpoint through the cache when forwarding GRPC request.
None.
> fix: add leader cache

- server/service/http/api.go
- server/service/http/error.go
Closes #
error messages in http api are not detailed enough
- modify response error message
- modify log error message
none
unit test & manual test
> refactor: error message in http api

- server/config/config.go
- server/limiter/limiter.go
- server/limiter/limiter_test.go
- server/service/http/api.go
Closes #
Friendly user
* Rename TokenBucketFillRate to Limit.
* Rename TokenBucketBurstEventCapacity to Burst.
none
CI
> refactor: rename limiter api

- go.mod
- go.sum
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/server.go
- server/storage/types.go
Closes #
We modified the persistent data `TopologyType` in the previous pull request. In order to avoid the user from manually operating the interface, we need to add compatible code
* Add compatible code for `TopologyType`
Avoid users manually operating the interface to be compatible with version changes
An old version of the persistent data was used for testing in the local environment.
> refactor: compatible with topology persistence

- Makefile
Closes #188 
avoid oom when run golangci-lint locally
update  golangci-lint versdion to 1.51
anyone run golangci-lint locally
manually
> chore: update golangci-lint version

- server/cluster/metadata/cluster_metadata_test.go
Closes #
Fix broken unit test.
* Fix `testUpdateClusterView`
None.
> test: fix test update cluster view

- server/coordinator/shard_picker.go
Closes #
Fix server panic when shard is not assigned.
* Add shardNodes check in `shard_picker.go`
None.
> fix: fix panic when shard is not assigned

- server/limiter/limiter.go
- server/limiter/limiter_test.go
- server/service/http/api.go
Closes #193 
in order to know flow limiter info when server is running
add api to read flow limiter info
none
Existing tests
> feat: add flow limiter read interface

- go.mod
- go.sum
- server/cluster/cluster.go
- server/cluster/manager.go
- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/types.go
- server/config/config.go
- server/coordinator/factory.go
- server/coordinator/procedure/error.go
- server/coordinator/procedure/manager_impl.go
- server/coordinator/procedure/operation/transferleader/batch_transfer_leader.go
- server/coordinator/procedure/operation/transferleader/batch_transfer_leader_test.go
- server/coordinator/procedure/operation/transferleader/transfer_leader.go
- server/coordinator/procedure/test/common.go
- server/coordinator/scheduler/assign_shard_scheduler.go
- server/coordinator/scheduler/assign_shard_scheduler_test.go
- server/coordinator/scheduler/rebalanced_shard_scheduler.go
- server/coordinator/scheduler/rebalanced_shard_scheduler_test.go
- server/coordinator/scheduler/scheduler_manager.go
- server/coordinator/scheduler/scheduler_manager_test.go
- server/coordinator/scheduler/static_topology_shard_scheduler.go
- server/coordinator/scheduler/static_topology_shard_scheduler_test.go
- server/server.go
- server/service/grpc/service.go
- server/service/http/api.go
- server/storage/types.go
Closes #173 
As it mentioned in issue, we need to support open shard concurrently to improve failover performence.
* Add `batch_transfer_leader`, it is used to open multiple shards concurrently in batches.
None.
> refactor: support open shard concurrently

- go.mod
- go.sum
- server/cluster/metadata/types.go
- server/coordinator/scheduler/reopen_shard_scheduler.go
- server/coordinator/scheduler/reopen_shard_scheduler_test.go
- server/coordinator/scheduler/scheduler_manager.go
- server/coordinator/scheduler/scheduler_manager_test.go
- server/storage/types.go
Closes #
At present, our implementation of shard opening is relatively simple. When some tables in a shard fail to open, it is impossible to retry and recover without restarting the CeresDB node. We need to solve this problem so that shards that fail to open some tables Can be recovered by retrying.
* Introduce the latest proto and add the definition of shard status.
* Add the implementation of `ReopenShardScheduler` for retrying partially opened shards.
None.
* Pass all unit tests and integration tests.
> feat: add reopen shard scheduler

- server/member/member.go
- server/server.go
- server/service/http/api.go
- server/service/http/error.go
- server/service/http/etcd_api.go
- server/service/http/forward.go
Closes #209 
At present, the peers IP of CeresMeta cannot be adjusted after the cluster initialization is completed, and the capacity cannot be expanded or contracted. If there is a node replacement or expansion or contraction, it needs to be manually operated through `etcdutil`. We need to add a management interface to solve this problem.
* Add ETCD member API. 
None.
> feat: add ETCD member API

- server/service/grpc/service.go
Closes #221 
As mentioned in issue, reduce the pressure of route requests on cpu.
* Remove error stack in gprc response header.
None.
No need.
> fix: remove gprc header error stack

- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/cluster_metadata_test.go
- server/cluster/metadata/topology_manager.go
…eturn error
Closes #
Avoid routing tables returning errors due to incorrect metadata.
Avoid routing tables returning errors due to incorrect metadata.
> refactor: avoid routing tables returning errors due to incorrect metadata

- server/cluster/metadata/cluster_metadata.go
- server/coordinator/scheduler/scheduler_manager.go
Closes #
Before the cluster state is stable, it is not allowed to create and delete tables to avoid uneven distribution of tables.
* Add cluster state check when create table & drop table.
None.
> fix: add cluster state check

- server/coordinator/factory.go
- server/coordinator/factory_test.go
- server/coordinator/procedure/ddl/createpartitiontable/create_partition_table.go
- server/coordinator/procedure/ddl/droppartitiontable/create_drop_partition_table_test.go
- server/coordinator/procedure/ddl/droppartitiontable/drop_partition_table.go
- server/coordinator/procedure/ddl/droptable/create_drop_table_test.go
- server/coordinator/procedure/ddl/droptable/drop_table.go
- server/service/grpc/service.go
Closes #
The shard is wrong when dropping a non-existent table.
Throw an error when the table to drop is not found.
None.
Manually.
> fix: wrong shard id when drop non-exist table

- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/table_manager.go
- server/coordinator/factory_test.go
- server/coordinator/procedure/ddl/common_util.go
- server/coordinator/procedure/ddl/createpartitiontable/create_partition_table.go
- server/coordinator/procedure/ddl/createtable/create_table.go
- server/coordinator/procedure/ddl/droppartitiontable/drop_partition_table.go
- server/coordinator/procedure/ddl/droptable/drop_table.go
- server/coordinator/procedure/manager_impl.go
- server/service/grpc/service.go
Closes #
Fixed the issue where the table could not be deleted normally when the shard mapping relationship of the table did not exist.
* Modified the logic about drop table.
* Add some logs to facilitate troubleshooting.
None.
> fix: drop partition table

- server/cluster/cluster.go
- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/topology_manager.go
- server/config/config.go
- server/coordinator/scheduler/reopen_shard_scheduler.go
- server/coordinator/scheduler/reopen_shard_scheduler_test.go
- server/service/http/api.go
- server/storage/types.go
Provides `disgnose/shards` api  to check cluster shards status.
* Refactor some code.
* Add `disgnose/shards` api.
```
curl 0:8080/api/v1/diagnose/defaultCluster/shards
{
"status": "success",
"data":
{
"shard_not_register":
{
"0": "127.0.0.1:8832",
"1": "127.0.0.1:8832",
"5": "127.0.0.1:8832",
"6": "127.0.0.1:8832"
},
"shard_not_ready":
{}
}
}
```
> feat: add diagnose/shards api

- server/cluster/metadata/types.go
- server/coordinator/procedure/ddl/droppartitiontable/drop_partition_table.go
Support concurrent deletion of partition subtables at the shard level.
* Dispatch drop partition sub table concurrently.
```
CREATE TABLE `demo1`(
`name`string TAG,
`id` int TAG,
`value` double NOT NULL,
`t` timestamp NOT NULL,
TIMESTAMP KEY(t)
) PARTITION BY KEY(name) PARTITIONS 400 ENGINE = Analytic
```
It takes 4 seconds to drop this partition table `demo1` which contains 400 sub-tables.
> feat: support drop partition table parallelly

- server/coordinator/scheduler/rebalanced_shard_scheduler.go
- server/coordinator/scheduler/rebalanced_shard_scheduler_test.go
Currently, the cluster state can't be stable after `AssignShardScheduler` is removed in #236. And this results from that the `RebalancedShardScheduler` won't schedule if the cluster state is not stable.
Allow the `RabalancedShardScheduler` to run on the unstable cluster.
Manual test.
> fix: allow rebalance scheduler to run on the unstable cluster

- server/member/watch_leader.go
- server/server.go
The endpoint of the leader persisted in the etcd is wrong.
Save the correct endpoint of the ceresmeta leader in the etcd.
Manual tests.
> chore: refactor some code

- server/coordinator/factory.go
- server/coordinator/procedure/ddl/createpartitiontable/create_partition_table_test.go
- server/coordinator/procedure/ddl/droppartitiontable/create_drop_partition_table_test.go
- server/coordinator/shard_picker.go
- server/coordinator/shard_picker_test.go
Currently, we use a completely random method to select shards for tables, which will lead to uneven distribution of tables in the cluster when the number of tables is small. In order to solve this problem, a new shardPicker is implemented, which selects the shard with the smallest number of current tables each time to create a table.
* Add `NewLeastTableShardPicker`, which selects the shard with the smallest number of current tables each time to create a table.
* Pass all unit tests and manually create tables for verification in the local environment.
> feat: add least table shard picker

- server/cluster/cluster.go
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/topology_manager.go
- server/service/http/api.go
- server/service/http/types.go
When a shard is not open on a node, the diagnose api returns incorrect information.
Modify the method of obtaining shards to no longer retrieve all shard information from the `nodeshards`.
> refactor: diagnose shards api

- server/service/http/api.go
- server/service/http/route.go
> There’s no rule on keeping the resource nouns singular or plural, though it is advisable to keep collections plural.
- https://swagger.io/resources/articles/best-practices-in-api-design/
No need.
> chore: use clusters in api endpoint

- server/config/config.go
- server/server.go
Fix wrong tls config.
Modify parameters according to official documentation: https://pkg.go.dev/github.com/coreos/etcd/clientv3#Config
* Fix wrong tls config.
Verify on etcd server with tls.
> fix: TLS config

- server/cluster/cluster.go
- server/coordinator/factory.go
- server/coordinator/factory_test.go
- server/coordinator/scheduler/manager/scheduler_manager_test.go
- server/coordinator/scheduler/rebalanced/scheduler_test.go
- server/coordinator/scheduler/reopen/scheduler_test.go
- server/coordinator/scheduler/static/scheduler_test.go
Fix panic caused by missing logger.
* Add `logger` in NewFactory.
> fix: logger panic

- go.mod
- server/cluster/metadata/cluster_metadata.go
- server/config/config.go
- server/storage/storage_impl.go
The external etcd server may have a limit on the number of operations in a transaction. However, CeresMeta don't impose such a limit when operating etcd, and it will lead to error.
Introduce such a limit on the number of operations in a transaction.
Existing tests.
> feat: support MaxOpsPerTxn for operate etcd

- server/coordinator/scheduler/static/scheduler.go
Fix return error when single node is not found in static topology, make it is possible to assign shards to nodes when a single node is not found.
Just continue instead of return error when single node is not found in static topology.
> fix: return error when single node is not found in static topology

- server/coordinator/procedure/test/common.go
- server/coordinator/shard_picker.go
- server/coordinator/shard_picker_test.go
We found that according to the current way of pick shards, the subtables of the partition table will be concentrated on some nodes, causing hot spots, so some modifications need to be made to avoid this phenomenon.
* Modify the logic of pick shard, when the number of tables is the same, sort according to the size of ShardID.
> fix: modify the logic of pick shards

- server/coordinator/procedure/operation/transferleader/transfer_leader.go
- server/storage/storage_impl.go
In the current implementation, a copy of the topology is stored every time the cluster topology is updated, but expired topology data has no effect and will cause a waste of ETCD storage space.
* Remove expired topology data when update cluster view.
> refactor: remove useless topology data

- server/service/http/api.go
The response is nil if there is no need to do http fowarding.
Only close the resp body if the http request needs forward.
Manual test.
> fix: nil resp if no need to forward

- scripts/run_integration_test.sh
This follows up https://github.com/CeresDB/ceresdb/pull/1287 and https://github.com/CeresDB/ceresmeta/pull/265.
> ci: catchup and simplify integrate test runner

- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/topology_manager.go
- server/coordinator/procedure/operation/transferleader/batch_transfer_leader.go
For detail, see: https://github.com/CeresDB/ceresmeta/issues/263
In this pr, add the checksum repair logic of shard version.
* Add `MayCorrectShardVersion` in `RegisterNode`, it will correct shard version when it is inconsistent in ceresmeta and ceresdb.
I created some local shard version inconsistent scenarios to verify its repair ability.
> refactor: correct shard version

- .github/workflows/check.yml
- go.mod
- go.sum
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/cluster_metadata_test.go
- server/cluster/metadata/error.go
- server/cluster/metadata/topology_manager.go
- server/cluster/metadata/topology_manager_test.go
- server/cluster/metadata/types.go
- server/coordinator/eventdispatch/dispatch.go
- server/coordinator/eventdispatch/dispatch_impl.go
- server/coordinator/procedure/ddl/common_util.go
- server/coordinator/procedure/ddl/createpartitiontable/create_partition_table.go
- server/coordinator/procedure/ddl/createtable/create_table.go
- server/coordinator/procedure/ddl/droppartitiontable/create_drop_partition_table_test.go
- server/coordinator/procedure/ddl/droppartitiontable/drop_partition_table.go
- server/coordinator/procedure/ddl/droptable/drop_table.go
- server/coordinator/procedure/operation/split/split_test.go
- server/coordinator/procedure/operation/transferleader/transfer_leader.go
- server/coordinator/procedure/test/common.go
- server/coordinator/shard_picker_test.go
- server/service/grpc/service.go
- server/storage/storage_impl.go
- server/storage/storage_test.go
- server/storage/types.go
Refer to this issue: https://github.com/CeresDB/ceresmeta/issues/263
* Reconstruct the process of create/drop table so that the update of shard version depends on CeresDB
Pass existing unit tests and integration tests.
> refactor!: refactor shard version logic

- server/cluster/metadata/topology_manager.go
Fix the problem of updating `shardview` in memory that existed in the previous pr https://github.com/CeresDB/ceresmeta/pull/268.
* Update `shardTableMapping` in memory.
> fix: fix update shard view

- server/config/config.go
- server/limiter/limiter.go
- server/service/http/api.go
- server/service/http/types.go
Ratelimiter is enabled by default to prevent ceresmeta from being hung.
Ratelimiter is enabled by default.
CI.
> chore: Ratelimiter is enabled by default

- scripts/run-integration-test.sh
Integration tests failed.
* Fix wrong env variable name.
CI.
> fix: wrong env variable in integration test

- server/cluster/cluster.go
- server/service/http/api.go
Due to misconfiguration of the ProcedureID Allocator storage path in ETCD, multiple clusters will share the same ProcedureID Allocator, which will cause ID to be wasted.
* Fix wrong ID allocator storage path.
Pass CI.
> fix: wrong procedure id allocator

- config/example-standalone.toml
- server/coordinator/factory.go
- server/coordinator/factory_test.go
- server/coordinator/procedure/ddl/createpartitiontable/create_partition_table.go
- server/coordinator/procedure/ddl/createtable/create_table.go
- server/coordinator/procedure/ddl/droppartitiontable/drop_partition_table.go
- server/coordinator/procedure/ddl/droptable/drop_table.go
- server/coordinator/procedure/delay_queue_test.go
- server/coordinator/procedure/manager_impl.go
- server/coordinator/procedure/manager_test.go
- server/coordinator/procedure/operation/split/split.go
- server/coordinator/procedure/operation/transferleader/batch_transfer_leader.go
- server/coordinator/procedure/operation/transferleader/batch_transfer_leader_test.go
- server/coordinator/procedure/operation/transferleader/transfer_leader.go
- server/coordinator/procedure/procedure.go
- server/coordinator/procedure/storage.go
- server/coordinator/procedure/storage_impl.go
- server/coordinator/procedure/storage_test.go
- server/coordinator/procedure/test/common.go
- server/id/id_impl.go
The current design of the procedure storage module is unreasonable. The data will be stored permanently and will not be cleared. This will cause the storage space of `ETCD` to be filled up quickly. We need to redesign the interface of procedure storage.
* Add `ttl` config for `CreateOrUpdate`.
* Add `Delete` interface, it used to delete history procedure data and current procedure data.
> refactor: procedure storage

- server/id/id.go
related https://github.com/CeresDB/horaedb/issues/1319
rename comment's ceresdb to horaedb
ci
> chore: rename comment's ceresdb to horaedb

- server/service/http/api.go
- server/service/http/error.go
- server/service/http/types.go
In some extreme cases (for this situation, please refer to https://github.com/apache/incubator-horaedb-meta/issues/296), the shard node cannot be cleaned normally, and we need to add an operation and maintenance interface to complete manual cleaning.
* Add drop shard node api.
Pass CI.
> feat: add drop shard node api

- go.mod
- go.sum
- server/server.go
- server/service/grpc/forward.go
- server/service/grpc/service.go
Upgrade horaedbproto.
Break changes:  Change `CeresmetaRpcService` to `MetaRpcService`.
Due to Break changes, CI cannot pass. It is necessary to merge the changes on the `horaemeta` side first, and then modify the `horaedb` side.
> feat!: upgrade horaedbproto

- pkg/coderr/error_test.go
- server/coordinator/procedure/ddl/createtable/create_table.go
- server/service/grpc/service.go
- server/service/http/api.go
- server/service/http/error.go
- server/service/http/types.go
Refer to: https://github.com/apache/incubator-horaedb/issues/1319, in order to facilitate development after the project was renamed, we split the dev branch. Now we need to merge the dev branch into the main branch.
* Merge dev branch to main branch.
Because the results of the horaemeta integration test depend on horaedb, the integration test won't pass until the horaedb dev branch is merged.
> chore: merge change sets on the dev branch

- server/coordinator/procedure/operation/transferleader/transfer_leader.go
Currently, the `TransferLeader` procedure will be persisted every time it is executed, but they actually have no effect. When the cluster runs for a long time, some garbage data will be generated to occupy ETCD's storage space.
* Remove useless procedure persist in `transfer_leader`.
Pass CI.
> refactor: remove useless procedure persist

- server/cluster/manager_test.go
- server/config/config.go
- server/coordinator/procedure/test/common.go
See https://github.com/apache/incubator-horaedb/issues/1319
This is a breaking change. users need to add following config to keep back-compatitble
```
storage-root-path = "/ceresdb"
```
Or set via env vars 
```
export STORAGE_ROOT_PATH="/ceresdb"
```
No need
> chore!: replace ceresdb with test

- server/cluster/cluster.go
- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/topology_manager.go
- server/coordinator/factory.go
- server/coordinator/factory_test.go
- server/coordinator/persist_shard_picker.go
- server/coordinator/persist_shard_picker_test.go
- server/coordinator/procedure/ddl/createtable/create_table.go
- server/coordinator/procedure/error.go
- server/coordinator/procedure/storage_impl.go
- server/coordinator/scheduler/manager/scheduler_manager_test.go
- server/coordinator/scheduler/rebalanced/scheduler_test.go
- server/coordinator/scheduler/reopen/scheduler_test.go
- server/coordinator/scheduler/static/scheduler_test.go
- server/etcdutil/util.go
- server/etcdutil/util_test.go
- server/storage/key_path.go
- server/storage/meta.go
- server/storage/storage_impl.go
- server/storage/types.go
Store the intermediate data for table creation through procedures to support idempotent table creation.
* Store the intermediate data for table creation through procedure.
* Supports retrying from the upper layer to complete failed table creation procedures.
> refactor: make create table idempotent
