apache/incubator-horaedb-meta

- README.md
- docs/style_guide.md
Closes #
More principles for logging style are necessary.
More principles and examples about logging style.
None.
No need.
> docs: improvement logging style_guide

- server/id/error.go
- server/id/id.go
- server/id/id_impl.go
- server/id/id_test.go
- server/storage/etcd_kv.go
- server/storage/kv.go
> feat: impl ID Allocator 

- go.mod
- go.sum
- pkg/coderr/code.go
- server/cluster/cluster.go
- server/cluster/coordinator.go
- server/cluster/error.go
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/cluster/node.go
- server/cluster/schema.go
- server/cluster/shard.go
- server/cluster/table.go
- server/grpcservice/service.go
- server/member/member.go
- server/schedule/hbstream.go
- server/server.go
- server/storage/key_path.go
- server/storage/meta.go
- server/storage/storage_impl.go
> feat: impl cluster supports static cluster topology

- server/cluster/cluster.go
- server/cluster/coordinator.go
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/schedule/event_handler.go
- server/server.go
Closes #27 
Send events through heartbeat response to CeresDB node, CeresDB node can change it's state by those events.
none
TODO: need to add tests
> feat(schedule): impl event_handler

- server/cluster/cluster.go
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/config/config.go
- server/id/error.go
- server/id/id_impl.go
- server/id/id_test.go
- server/server.go
Closes #
Refactor ID Allocator with etcdKV.
no
Refactor test in server/id/id_test.go
> refactor(idAllocator): refactor id allocator

- server/cluster/cluster.go
- server/cluster/coordinator.go
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/server.go
Close #
Refer to #34
Impl start and stop of cluster manager.
no
Tests in manager_test.go should run manager.start() before testing cluster manager.
> feat(cluster): impl start&stop of cluster manager

- server/config/config.go
- server/server.go
Closes #
Refer to #33 
Add createDefaultCluster of Server.
no
no need
> feat(server): add createDefaultCluster of Server

- go.mod
- go.sum
- server/cluster/cluster.go
- server/cluster/coordinator.go
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/cluster/shard.go
- server/grpcservice/service.go
- server/server.go
- server/storage/storage_impl.go
- server/storage/storage_test.go
Closes #
Impl RouteTable of grpc server.
Impl RouteTable of grpc server.
Add `testRouteTables` in server/cluster/manager_test.go.
> feat: impl RouteTable of grpc server

- pkg/coderr/code.go
- pkg/coderr/error.go
- server/cluster/cluster.go
- server/cluster/coordinator.go
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/grpcservice/util.go
- server/server.go
Closes #
Ceresmeta will send `opencmd` when the node  dose not open shard.
no
no need
> feat: support scatterShard when clusterState is stable

- server/server.go
Closes #
When the leader of ceresemta is transformed, the meta server needs to start or stop to release resources.
Implements `LeadershipEventCallbacks` interface of ceresmeta server.
no
no
> feat: impl `LeadershipEventCallbacks` interface of Server

- go.mod
- go.sum
- server/cluster/coordinator.go
- server/cluster/manager.go
- server/grpcservice/forward.go
- server/grpcservice/service.go
- server/grpcservice/util.go
- server/member/member.go
- server/member/watch_leader_test.go
- server/server.go
Closes #
Fix some bugs in integration tests with ceresdb-server.
Fix forward request bug.
> fix(grpcservice): fix forward request bug

- go.mod
- go.sum
- server/cluster/cluster.go
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/grpcservice/service.go
Closes #
impl GetNodes of grpc server.
> feat:impl GetNodes of grpc server

- README.md
Closes #
Readme has mistakes.
fixed readme.
None.
Run as what readme suggests.
> chore: Refactor readme

- server/cluster/manager.go
- server/cluster/manager_test.go
Closes #
existed bug in manager_test & manager
fix manager_test & add clientv3 in manager
none
exited UT
> fix: fix manager_test & manager

- server/cluster/manager_test.go
- server/etcdutil/config.go
- server/etcdutil/get_leader.go
- server/etcdutil/impl.go
- server/etcdutil/interface.go
- server/etcdutil/util.go
- server/etcdutil/util_test.go
- server/id/id_test.go
- server/member/watch_leader_test.go
- server/storage/storage_impl.go
Closes #
After adding some unit tests for `Scan` method in the `etcdutil` package, some bugs has been found. Fix them and refactor the method.
- Refactor `Scan` method in `etcdutil` package.
- Add unit test for `Scan` method.
None.
New unit tests.
> refactor: Scan util method for etcdclient

- Makefile
- scripts/check-license.sh
- server/cluster/fsm_test.go
- server/schedule/error.go
Closes #
We are missing a way to check the file header license.
Use a script to check the file header license.
Refer to https://github.com/tikv/tikv/commit/8be0b14d34382eaa7ff9814714af19043547466e
Thanks tikv.
> feat: add check-license script

- server/cluster/cluster.go
- server/cluster/error.go
- server/coordinator/procedure/scatter.go
- server/coordinator/procedure/scatter_test.go
https://github.com/CeresDB/ceresmeta/issues/66
As mentioned in issue, add a procedure implementation
Add `ScatterProcedure` implementation.
None.
> feat: add scatter procedure

- go.mod
- go.sum
- server/cluster/cluster.go
- server/cluster/manager_test.go
- server/cluster/types.go
- server/coordinator/procedure/scatter.go
- server/coordinator/procedure/shard/fsm.go
- server/coordinator/procedure/transfer_leader.go
- server/service/grpc/service.go
Closes #
Upgrade ceresdbproto to latest version.
* Modify `GetShardTables` to `GetTablesOfShards`.
> feat: upgrade ceresdbproto to latest version

- server/coordinator/procedure/create_drop_table_test.go
- server/coordinator/procedure/create_table.go
- server/coordinator/procedure/drop_table.go
- server/coordinator/procedure/procedure.go
- server/storage/storage_impl.go
Closes #
Add DropTableProcedure implementation.
Add DropTableProcedure implementation.
No.
Add `TestCreateAndDropTable` test to test it.
> feat: add DropTableProcedure

- go.mod
- go.sum
- server/cluster/cluster.go
- server/cluster/error.go
- server/cluster/manager.go
- server/cluster/shard.go
- server/cluster/types.go
- server/coordinator/eventdispatch/dispatch.go
- server/coordinator/eventdispatch/dispatch_impl.go
- server/coordinator/procedure/create_drop_table_test.go
- server/coordinator/procedure/create_table.go
- server/coordinator/procedure/drop_table.go
- server/coordinator/procedure/factory.go
- server/storage/storage_impl.go
Closes #
Upgrade ceresdbproto to latest version.
* Modify `GetOrCreateTable` to `CreateTable`
*
> chore: upgrade ceresdbproto to latest version

- server/cluster/cluster.go
- server/cluster/table.go
- server/cluster/types.go
- server/coordinator/procedure/create_drop_table_test.go
- server/coordinator/procedure/create_table.go
- server/coordinator/procedure/drop_table.go
- server/coordinator/procedure/factory.go
- server/server.go
- server/service/grpc/service.go
Closes #
Implement `CreateTable` and `DropTable` in gRPC `CeresmetaServer`.
* Implement `CreateTable` in gRPC `CeresmetaServer`
* Implement `DropTable` in gRPC `CeresmetaServer`
No.
> feat: impl create and drop table service

- server/cluster/cluster.go
- server/cluster/manager.go
- server/cluster/manager_test.go
- server/cluster/node.go
- server/cluster/shard.go
- server/cluster/types.go
- server/coordinator/procedure/scatter.go
- server/coordinator/procedure/scatter_test.go
- server/server.go
Closes #
For now, `nodeCache` is shared by topology and registering, which is confusing.
- Add new cache: `registeredNodeCache` to manage registering information.
None.
Test by manual.
> feat: support manage registered nodes

- server/service/grpc/service.go
Closes #95 
Fix create/drop table request forward bug.
Add request forward in `CreateTable` & `DropTable`.
None.
> fix: forward create/drop table request to leader

- server/cluster/table_manager.go
- server/cluster/topology_manager.go
Closes #
Add some debugging information when the cluster loads metadata to find troubleshooting of potential metadata errors.
Add some debug info when cluster load metadata.
No.
No need to test.
> chore: add some debug info when cluster load metadata

- server/cluster/cluster.go
- server/cluster/manager.go
- server/coordinator/procedure/create_drop_table_test.go
Closes #
Modify test to cover bug fixed in #108  
Modify TestCreateAndDropTable test.
No.
> test: modify TestCreateAndDropTable test

- go.mod
- go.sum
- server/storage/storage_impl.go
- server/storage/types.go
Closes #
Update the pb dependency in ceresmeta to be consistent with the ceresproto version.
* Update ceresproto version.
* Refactor types definition, keep same with ceresproto.
None.
> refactor: update pb definition

- .github/workflows/check.yml
- .gitignore
- Makefile
- README.md
Closes #
Add `codecov` to show test coverage report.
Add `codecov` to show test coverage report.
No.
No need.
> chore: add codecov

- README.md
- config/example-cluster0.toml
- config/example-cluster1.toml
- config/example-cluster2.toml
- config/example-standalone.toml
Closes #
Update meta addr in example-cluster config for better deployment.
* Update meta addr in example-cluster config for better deployment.
* Update `Readme`.
No.
No need.
> docs: update example config

- go.mod
- server/config/config.go
- server/service/http/api.go
Closes #130 
Use json to format http return results to increase readability.
* Use json to format http return results.
Beautify the http response
Manual testing.
> chore: beautify the http response

- server/member/member.go
- server/service/grpc/service.go
Closes #
Add some logs for debugging and monitoring.
* Add some info logs in gprc service.
* Change set leader log in member.
None.
> refactor: add some logs

- .github/workflows/check.yml
Closes #
Update CI config, All branches will run CI.
* Update `check.yml`
None.
No need.
> chore: update CI branch config

- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/topology_manager.go
- server/config/config.go
- server/coordinator/procedure/ddl/common_util.go
- server/coordinator/procedure/ddl/createpartitiontable/create_partition_table.go
- server/coordinator/procedure/ddl/createtable/create_table.go
- server/coordinator/procedure/ddl/droppartitiontable/drop_partition_table.go
- server/coordinator/procedure/ddl/droptable/drop_table.go
- server/coordinator/procedure/manager_impl.go
- server/coordinator/procedure/operation/transferleader/transfer_leader.go
- server/coordinator/watch/watch.go
- server/coordinator/watch/watch_test.go
- server/service/http/api.go
Closes #
Refactor shard version related modules based on the latest design. 
* Adjusted the shard version update order of CeresMeta metadata and CeresDB.
* Implement the version verification of procedure in ProcedureManager.
None.
> refactor: refactor shard version check

- server/server.go
- server/service/http/api.go
- server/service/http/error.go
- server/status/status.go
Closes #
Add meta health check api for k8s ops.
local test is passed
> feat: add health check api

- server/cluster/metadata/cluster_metadata.go
Closes #
Fix wrong return result in compare.
* Fix wrong return result in compare.
None.
> fix: fix compare result

- server/cluster/metadata/cluster_metadata.go
Closes #
Fix the problem of node registration.
* Fixed the problem where nodes were updated in the wrong order in `RegisterNode`.
None.
> fix: fix register node

- .github/codecov.yml
> chore: add codecov.yml

- server/service/http/api.go
Closes #
Add pprof debug API.
* Add pprof debug API.
None.
Manual testing in local environment.
> refactor: add pprof debug API

- server/cluster/manager.go
- server/cluster/metadata/types.go
- server/service/http/api.go
- server/service/http/route.go
Closes #
Refactor cluster-related interfaces to make the interface design more reasonable. 
* Modify the path of the HTTP interface.
* Support change cluster topology.
None.
> refactor: refactor cluster interface

- server/service/http/api.go
Closes #
Duplicate error message in http api.
http api error message
none
CI
> refactor: error message

- server/coordinator/scheduler/rebalanced_shard_scheduler_test.go
Closes #
Test case has a partial probability of failure.
remove partial probability of failure test code.
none
CI
> fix: remove test code

- server/coordinator/procedure/ddl/createtable/create_table.go
- server/coordinator/procedure/ddl/droptable/drop_table.go
- server/coordinator/procedure/operation/transferleader/transfer_leader.go
- server/coordinator/scheduler/assign_shard_scheduler.go
- server/service/http/api.go
- server/service/http/forward.go
Closes #
Optimize the http interface, remove useless parameters, and add some necessary logs.
* Add forward logic to `transferLeader` and `getShardTables`.
* Automatically fill the parameters of getShardTables, when no shard is specified, output all shards.
* Add `getLeader` interface.
* Add some necessary logs.
None.
> refactor: refactor http api module

- .github/workflows/dockerhub-publish-nighty.yml
Closes #
Add nighty docker image workflow.
* Add nighty docker image workflow.
None.
No need to test.
> chore: add nighty builder

- .github/codecov.yml
Closes #
Fix the code cov problem, there is a problem with the current baseline, the expired code is used, the baseline is not updated.
* Fix code cov config.
None.
No need to test.
> fix: fix codecov

- server/cluster/manager.go
- server/service/http/api.go
- server/service/http/etcd_api.go
Closes #
Refactor the api module and encapsulate the repeated code as a wrapper.
* Add `wrap` function in `api.go`, it is used to encapsulate result processing logic and request forwarding logic.
* Refactor api module based on `wrap` function.
None.
> refactor: refactor api module

- .gitignore
- Makefile
- cmd/meta/main.go
- server/config/config.go
Closes #
Add tool to output version.
None.
manual testing.
> chore: add version print

- go.mod
- go.sum
Closes #
The ceresdbproto is stale.
Upgrade the ceresdbproto.
None.
No need.
> chore: ugprade the ceresdbproto

- server/config/config.go
Remove useless code.
Remove `GenLogConfigConfig`.
CI.
> chore: remove useless code

- server/cluster/manager.go
- server/cluster/manager_test.go
- server/cluster/metadata/cluster_metadata.go
- server/cluster/metadata/table_manager.go
- server/cluster/metadata/table_manager_test.go
- server/cluster/metadata/types.go
- server/coordinator/procedure/ddl/common_util.go
- server/coordinator/procedure/ddl/droptable/drop_table.go
- server/service/grpc/service.go
- server/service/http/api.go
- server/service/http/error.go
- server/service/http/route.go
- server/storage/types.go
Add some operation  apis to better troubleshoot problems.
* return `createAt` when query shardTables
* add `table/query` api
> chore: add some operation apis

- server/service/http/api.go
- server/service/http/etcd_api.go
- server/service/http/forward.go
- server/service/http/types.go
Refactor http model.
* Move some types into `types.go` file.
* Reorganize function order.
CI.
> refactor: http mod

- config/example-cluster0.toml
- config/example-cluster1.toml
- config/example-cluster2.toml
- go.mod
- go.sum
- server/config/config.go
- server/etcdutil/get_leader.go
- server/member/member.go
- server/member/watch_leader.go
- server/member/watch_leader_test.go
- server/server.go
- server/service/grpc/forward.go
Support external etcd cluster.
* Add option to enable embed etcd cluster.
* [Breaking change] rename `default-http-port` to `http-port`.
> feat: support external etcd

- server/cluster/manager_test.go
- server/cluster/metadata/table_manager_test.go
- server/cluster/metadata/topology_manager_test.go
- server/coordinator/procedure/test/common.go
- server/server.go
- server/storage/storage_test.go
The MaxOpsPerTxn is not set.
Set the MaxOpsPerTxn.
CI.
> fix: unset the MaxOpsPerTxn

- go.mod
Ref -
* Fix https://github.com/CeresDB/ceresdb/issues/1274
* https://github.com/golang/go/issues/61888
> chore: fix golang version pattern in go.mod

- .github/workflows/check.yml
- Makefile
- scripts/run-integration-test.sh
- scripts/run_integration_test.sh
The current integration-test does not use the code submitted in this PR for ceresmeta-server.
Use the code in this PR for ceresmeta-server.
CI.
> ci: fix integration-test

- config/example-standalone.toml
- go.sum
- pkg/coderr/error_test.go
- scripts/run-integration-test.sh
- server/cluster/cluster.go
- server/coordinator/factory.go
- server/coordinator/factory_test.go
- server/coordinator/procedure/ddl/createpartitiontable/create_partition_table.go
- server/coordinator/procedure/ddl/createtable/create_table.go
- server/coordinator/procedure/ddl/droppartitiontable/drop_partition_table.go
- server/coordinator/procedure/ddl/droptable/drop_table.go
- server/coordinator/procedure/delay_queue_test.go
- server/coordinator/procedure/manager_impl.go
- server/coordinator/procedure/manager_test.go
- server/coordinator/procedure/operation/split/split.go
- server/coordinator/procedure/operation/transferleader/batch_transfer_leader.go
- server/coordinator/procedure/operation/transferleader/batch_transfer_leader_test.go
- server/coordinator/procedure/operation/transferleader/transfer_leader.go
- server/coordinator/procedure/procedure.go
- server/coordinator/procedure/storage.go
- server/coordinator/procedure/storage_impl.go
- server/coordinator/procedure/storage_test.go
- server/coordinator/procedure/test/common.go
- server/id/id_impl.go
- server/service/http/api.go
Currently the tests on the dev branch are not running properly.
* Cherry pick some changes on main branch.
* Fix integration test.
Pass CI.
> fix: fix integration tests on dev branch

- .asf.yaml
> chore: add asf yaml

- .github/workflows/publish-nightly-image.yml
Fix publish nightly image.
No need.
> chore: fix publish nightly image

- .asf.yaml
> chore: update website url

- CONTRIBUTING.md
> chore: fix broken link
